### ISSUE TITLE
[Feature] Player movement and bomb placing

### ISSUE THREAD

**Issue by R4fau** [mateuszCabala95/CodersCamp2020.Bomberman#16]

**Comment by R4fau** [comment]
My draft concept of player class. When it moves, a PlayerPresenceState properties of specific board fields also change.

[player.txt](https://github.com/mateuszCabala95/CodersCamp2020.Bomberman/files/5861205/player.txt)

**Comment by kgutka** [comment]
Board with 2 players is already implemented on `board-prototype` branch, game has event listener, it reacts on specific keys. The implementation of the game engine is based on [Building a game with TypeScript](https://medium.com/javascript-in-plain-english/gamedev-patterns-and-algorithms-in-action-with-typescript-d29b913858e)
