### ISSUE TITLE
Make a wireframe

### ISSUE THREAD

**Issue by mateuszCabala95** [mateuszCabala95/CodersCamp2020.Bomberman#2]
Wireframe to luźny szkic projektu. Bez żadnych styli, kolorów, ani rozmiarów fontów.
Link do tutorialu [Wireframe](https://www.youtube.com/watch?v=pN92rnO_n5U) i drug aczesc kursu [Wireframe UI](https://www.youtube.com/watch?v=_P3CrgFlXhg)

**Comment by kgutka** [comment]
Można uznać że zrobione? - [Figma](https://www.figma.com/file/t8WQq0rSHmscamBAWFyLaF/Untitled?node-id=0%3A1)
Czy jeszcze coś do tego dołożyć?

**Comment by mateuszCabala95** [comment]
Zastanowił bym się czy obok pająka nie dodać napisu "change character", bo o ile wiadomo, że koło zębate to ustawienia, to pająk nie koniecznie kojarzy się ze zmianą wyglądu, i pytanie czy w **page 3 ** ma być inny wygląd buttona PLAY niż w page 1 ?

**Comment by kgutka** [comment]
Opisałam w issue, ze po najechaniu na koło zębate żeby pojawiał się napis ustawienia (to jest na kolejnym linku - kolejny szablon) i w ten sam sposób zmiana postaci.
Co do buttona - page 2 i page 3 pokazują button po najechaniu na niego kursorem, page 1 domyślny - to jest też niżej w issue napisane

**Comment by mateuszCabala95** [comment]
OK dzięki
