### ISSUE TITLE
Detect if user is using a phone

### ISSUE THREAD

**Issue by kgutka** [mateuszCabala95/CodersCamp2020.Bomberman#4]
Check if user is on the phone while playing our game

**Comment by mateuszCabala95** [comment]
Here I recommend use [Modernizr](https://modernizr.com/)

**Comment by adam-kostuch** [comment]
- [ ] Install `webpack-modernizr-loader` 
- [ ] Add it to webpack
- [ ] Make configuration in `src/.modernizrrc.ts`
- [ ] Make new modernizr service in `src/services`
- [ ] Add it to `src/services/provider.ts`
