### ISSUE TITLE
[Feature] Main page

### ISSUE THREAD

**Issue by kgutka** [mateuszCabala95/CodersCamp2020.Bomberman#6]
### **Basics** 

- [x] Background color: #292929
- [x] For name of a game use font: `Sarpanch`, semibold with white (`#FFFFFF`) and blue (`#1A90FF`) color
- [x] rest of text should use font Lato
- [x] when chosen a game with friend (opponent) then input with nickname of 2. person appears - [schema](https://www.figma.com/file/t8WQq0rSHmscamBAWFyLaF/Untitled?node-id=4%3A9)

**Responsivity**
- [x] Hover button --> reverse colors (white button with blue text)
- [ ] After hover on gear the "settings" should be displayed, hover on character - "change character", [schema](https://www.figma.com/file/t8WQq0rSHmscamBAWFyLaF/Untitled?node-id=4%3A7)
- [ ] if it's possible add animation to div with "nickname", [example](https://css-tricks.com/snippets/css/typewriter-effect/)

**Comment by kgutka** [comment]
Updated schema and task list with muliplayer option

**Comment by mateuszCabala95** [comment]
- narazie nie dodałem ikonek settins ani change character
- animacje dodałem na tekst pod tytuł
- do zrobienia zostały jeszcze media query
